version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - pytest tests/test_basic.py
  post_build:
    commands:
      - zip -r artifact.zip .
artifacts:
  files:
    - artifact.zip
